services:
  recipe_api:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - target: 8000
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: .
        target: /cooking_recipe_api
      - type: volume
        target: /cooking_recipe_api/.venv
      - type: volume
        source: static_data
        target: /mnt/django/web
    working_dir: /cooking_recipe_api/src
    command:
      - sh
      - -c
      - python manage.py wait_for_db && python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    networks:
      - recipe_net
    environment:
      - POSTGRES_HOST=recipe_postgres
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=5432
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG:-False}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-}
      - DOCKER=true
    depends_on:
      - recipe_postgres

  recipe_postgres:
    image: postgres:18.2
    container_name: recipe_postgres
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - recipe_net
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres_data:
    driver: local
  static_data:
    driver: local

networks:
  recipe_net:
    driver: bridge
