[project]
name = "cooking-recipe-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=6.0.2",
    "djangorestframework>=3.16.1",
    "psycopg[binary,pool]>=3.3.2",
]

[dependency-groups]
dev = [
    "django-stubs>=5.2.9",
    "djangorestframework-stubs>=3.16.8",
    "pyrefly>=0.52.0",
    "python-dotenv>=1.2.1",
    "ruff>=0.15.1",
]


[tool.ruff]
target-version = "py314"
exclude = ["migrations", "manage.py", "settings.py"]

[tool.ruff.lint]
select = [
    # pycodestyle err
    "E",
    # Pyflakes
    "F",
    # pycodestyle warn
    "W",
    # isort
    "I",
    # Django rules
    "DJ",
]
