[project]
name = "cooking-recipe-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django==6.0.2",
    "djangorestframework==3.16.1",
    "drf-spectacular==0.29.0",
    "psycopg[binary,pool]==3.3.3",
]

[dependency-groups]
dev = [
    "django-stubs-ext==5.2.9",
    "django-types==0.23.0",
    "djangorestframework-types==0.9.0",
    "pyrefly==0.53.0",
    "python-dotenv==1.2.1",
    "ruff==0.15.2",
]


[tool.ruff]
target-version = "py314"
exclude = ["migrations", "manage.py", "settings.py"]

[tool.ruff.lint]
select = [
    # pycodestyle error
    "E",
    # Pyflakes
    "F",
    # pycodestyle warning
    "W",
    # isort
    "I",
    # Django rules
    "DJ",
]
ignore = [
    # Ignore line length for comments
    "E501",
]
