[project]
name = "cooking-recipe-api"
version = "0.0.4"
description = "A Django REST API for managing cooking recipes with PostgreSQL and token-based authentication."
readme = "README.md"
requires-python = ">=3.13"
authors = [{ name = "dongju93", email = "spdlqj011@gmail.com" }]
license = { text = "MIT" }
keywords = ["django", "rest-api", "recipe", "cooking", "postgresql", "drf"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: Django :: 6.0",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Topic :: Internet :: WWW/HTTP :: WSGI :: Application",
]
dependencies = [
    "django==6.0.3",
    "djangorestframework==3.16.1",
    "drf-spectacular==0.29.0",
    "psycopg[binary,pool]==3.3.3",
]

[dependency-groups]
dev = [
    "django-stubs-ext==5.2.9",
    "django-types==0.23.0",
    "djangorestframework-types==0.9.0",
    "pyrefly==0.55.0",
    "python-dotenv==1.2.2",
    "ruff==0.15.4",
]


[tool.ruff]
target-version = "py314"
exclude = ["migrations", "manage.py", "settings.py"]

[tool.ruff.lint]
select = [
    # pycodestyle error
    "E",
    # Pyflakes
    "F",
    # pycodestyle warning
    "W",
    # isort
    "I",
    # Django rules
    "DJ",
]
ignore = [
    # Ignore line length for comments
    "E501",
]
